version: "2.2"
services:
  postgres:
    image: postgres:14
    command: postgres -c 'max_connections=1024'
    environment:
      - POSTGRES_USER=dboperator
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    cpus: 2
    mem_limit: 4096m
    ports:
      - "5243:5432"
