version: "3.3"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=dboperator
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5243:5432"
