version: "2.2"
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=dboperator
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    cpus: 4
    mem_limit: 16384m
    ports:
      - "5243:5432"
